// Bővített minta adatok a napelem CRM-hez
export const SAMPLE_DATA = {
  munkalapok: [
    {
      id: "T003699/ML005781",
      ugyszam: "T003699",
      cimke: "Junior Vital",
      cimkeSzin: "#2563EB",
      status: "Megkezdésre Vár",
      statusSzin: "#38BDF8",
      projektMegnevezes: "Gedát ügyfél biztosítja a helyszínre!",
      feladat: "Napelem telepítés + akkumulátor",
      clientId: "c2",
      date: "2026-05-28",
      assigneeId: "u2",
      ertekesito: "Révész Roland",
      description: "11 panel lapos tetős telepítés akkumulátorral.",
      anyagok: [
        { nev: "Risen Energy RMS108-9-425N", menny: 11, egyseg: "db" },
        { nev: "Deye - SUN-5K-SG05LP3-EU-SM2", menny: 1, egyseg: "db" },
        { nev: "Solplanet Smart Meter Eastron SDM630", menny: 1, egyseg: "db" },
        { nev: "AC 3 fázisú túlfeszültség levezető T1+T2", menny: 1, egyseg: "db" },
        { nev: "DC túlfeszültség levezető T1+T2", menny: 1, egyseg: "db" },
        { nev: "Allwell Tűzeseti leválasztó AFS 2 string", menny: 1, egyseg: "db" },
        { nev: "TIGO TS4 Optimalizáló", menny: 11, egyseg: "db" },
        { nev: "PCEnersys LfePo4 akkumulátor M16S200BL-V5 10.24kWh", menny: 1, egyseg: "db" },
      ],
      felmeres: {
        csatlakozasiPont: "Most még nincs fix helye, de a garázs helyiségben lesz kialakítva",
        csatlPontAllapota: "felújítás szükséges ügyfél végzi",
        acKabelHossz: 12,
        acVedelem: "AC BOX T1+T2 3 fázis 25A",
        kommKabelHossz: 12,
        inverterFal: "Beltérben, garázs helyiségben tégla falazaton. Ügyfél telepíti a tartószerkezetet.",
        akkuFal: "Beltérben, garázs helyiségben tégla falazaton, inverter alá",
        akkuKabelHossz: 5,
        tetoTipus: "Lapos tető",
        tetoszerkezetTipus: "kaviccsal szórt szigetelt födém",
        padlas: "Járhatatlan",
        villamharitor: "Nincs",
        tartoszerkezetTipus: "Clenergy beton kockás tartó",
        potcserep: "Nem szükséges a kiválasztott tetőtípushoz",
        dcKabelHossz: 18,
        dcKabelNyomvonal: 10,
        dcVedelem: "DC BOX T1+T2 1MPPT 2ST",
        tuzKapcsolo: "Szükséges",
        panelElrendezes: "Lapos tetős telepítés, 11 panel beton kockás tartóval. Csillagba kötve.",
        felhordoEszkoz: "6 méter feletti GEDA szükséges",
        engedelyeztetes: "Fővállalkozó végzi az engedélyeztetést",
        visszwatt: "Fővállalkozó végzi az engedélyeztetést",
        megkozelithetoseg: "DC kábelt hátul, az udvar felől tudjuk levezetni az inverterre",
        felmeresIdopont: "2026-05-13",
      },
      items: [
        { name: "Napelem rendszer telepítés", qty: 1, unit: "db", net: 850000, vat: 27 },
        { name: "Anyagköltség", qty: 1, unit: "db", net: 1200000, vat: 27 },
      ],
    },
    {
      id: "T003680",
      ugyszam: "T003680",
      cimke: "Saját Önerős",
      cimkeSzin: "#059669",
      status: "Ütemezett",
      statusSzin: "#D97706",
      projektMegnevezes: "",
      feladat: "Napelem telepítés",
      clientId: "c1",
      date: "2026-05-26",
      assigneeId: "u3",
      ertekesito: "Bakonyi Patrik",
      description: "Külterületi telepítés.",
      anyagok: [],
      felmeres: {},
      items: [
        { name: "Napelem telepítés", qty: 1, unit: "db", net: 650000, vat: 27 },
      ],
    },
  ],
  ugyfelek: [
    { id: "c1", name: "Schamschula Virág", phone: "+36701234567", email: "schamschula@gmail.com", address: "5700 Gyula, Külterület 0548/6 Hrsz", type: "Magánszemély" },
    { id: "c2", name: "Nagy Zsolt", phone: "36306954999", email: "nincs@gmail.com", address: "6723 Szeged, Gém utca 11/C", type: "Magánszemély" },
    { id: "c3", name: "Fekete Kft.", phone: "+36204567890", email: "iroda@fekete.hu", address: "Piac utca 5., Debrecen", type: "Vállalkozás" },
  ],
};
