/**
 * projekt.schema.js
 * Re-exportálja a workflowRules.js-ből a projekt-specifikus konstansokat,
 * és definiálja az adatmodellt.
 */

export {
  PROJEKT_STATUSZOK,
  PROJEKT_FORRAS,
  LEGACY_PROJEKT_STATUS_MAP as LEGACY_STATUS_MAP,
  LEGACY_FORRAS_MAP,
  getProjektStatusConfig as getStatusConfig,
  getProjektStatusConfig,
  getProjektTipus,
  migrateProjektStatus,
  migrateProjektForras,
} from "../../lib/workflowRules.js";

export const PROJEKT_SCHEMA_VERSION = "2.0";

export const PROJEKT_TIPUSOK = [
  "Napelem telepítés",
  "Napelem csere",
  "Akkumulátor telepítés",
  "Szerviz / karbantartás",
  "Felmérés",
  "Garanciális munka",
  "Egyéb",
];

export const PROJEKT_SCHEMA = {
  id:                  "",
  projektkod:          "",
  kulsoAzonosito:      "",
  nev:                 "",
  clientId:            null,
  megbizoCeg:          "",
  clientNev:           "",
  clientCim:           "",
  clientTel:           "",
  clientEmail:         "",
  kapcsolattarto:      "",
  telepitesiCim:       "",
  tipus:               "Napelem telepítés",
  status:              "Létrehozva",
  napelemDb:           0,
  inverterDb:          0,
  akkumulatorDb:       0,
  smartMeterDb:        0,
  akkumulator:         false,
  okosmerő:            false,
  autoTolto:           false,
  projektvezetoId:     "",
  projektvezetoNev:    "",
  csapatId:            "",
  csapatNev:           "",
  tervezettKezdes:     "",
  tervezettBefejezes:  "",
  valoKezdes:          "",
  valoBefejezes:       "",
  elvegzettMunkaora:   0,
  munkalapIds:         [],
  dokumentumIds:       [],
  elfogadottAjanlat:   0,
  megjegyzesek:        [],
  esemenynaplo:        [],
  forrás:              "",
  projektTipus:        "",
  ajanlatId:           null,
  fovKapcsolattarto:   "",
  fovFizetesiHatarido: "",
  fovMegjegyzes:       "",
  driveProjektMappa:   "",
  createdAt:           "",
  updatedAt:           "",
  createdBy:           "",
  updatedBy:           "",
  version:             1,
  syncStatus:          "synced",
};
